# Open Weather Map Config
cityID = 'YOUR CITY ID'
APIkey = 'YOUR API KEY HERE'


# email stuff
SMTP_SERVER = 'YOUR SMTP SERVER'
SMTP_PORT = 'YOUR PORT'
SMTP_USERNAME = 'YOUR USERNAME'
SMTP_PASSWORD = 'YOUR PASSWORD'
EMAIL_FROM = 'YOUR EMAIL ADDRESS'
EMAIL_TO = {'Lows': 'RECIPIENTS', 'Rain': 'RECIPIENTS'}